@port = 5000
@baseUrl = http://localhost:{{port}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2EyNTBjZTdkM2UxNGVmZmRmNzFkNmUiLCJlbWFpbCI6ImNhdEBnbWFpbC5jb20iLCJuYW1lIjoiY2F0IiwiaWF0IjoxNzM4Njk3NDQyLCJleHAiOjE3Mzg2OTc3NDJ9.2kZR21es9hQVf4ct6KaWKcIIMKQE0I-PqW6G2OIS5dg
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk5MTA3NmI4OTRlMjI2ZDc3ZTc5MTciLCJlbWFpbCI6Im5ldy11c2VyQG1haWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiJlZDc2YjNjNi1iMzBlLTRkMjEtYWQ5NC04Y2ZkY2YyMDA2ODMiLCJpYXQiOjE3MzgwODUwNDgsImV4cCI6MTc0MDY3NzA0OH0.xQS4xNeNy0_GQZTISYJ_cb8Lmbb4_MK32DBadySBPec
@userId = 67991076b894e226d77e7917
@postId = cm6i9k2tn0002s160k44mfcsv
@commentId = 0c73cc7e-330b-4948-b203-7a4ca0e15ebc

# Новый пользователь
POST {{baseUrl}}/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "email@local.com",
  "name": "Alice",
  "password": "123456"
}

###
# Вход в систему
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user111@notfound.local",
  "password": "123456"
}

###
# Новый токен
POST {{baseUrl}}/users/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}

###
# Подписка
POST {{baseUrl}}/blog/feed/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "67a250ce7d3e14effdf71d6e"
}

###
# Отписка
POST {{baseUrl}}/blog/feed/unsubscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "67a250ce7d3e14effdf71d6e"
}

###
# Моя лента
GET {{baseUrl}}/blog/feed HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###
# Лайк
POST {{baseUrl}}/blog/posts/{{postId}}/likes HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "67991076b894e226d77e7917"
}

###
# Дизлайк
POST {{baseUrl}}/blog/posts/{{postId}}/likes HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "67991076b894e226d77e7917"
}

### Комментарии
# Создать комментарий
POST {{baseUrl}}/blog/posts/{{postId}}/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "message": "New Comment from gateway!"
}

###
# Список комментариев
GET {{baseUrl}}/blog/posts/{{postId}}/comments?page=1 HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# удалить комментарий
DELETE {{baseUrl}}/blog/posts/{{postId}}/comments/{{commentId}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# Рассылка о новых постах
POST {{baseUrl}}/notify HTTP/1.1
Authorization: Bearer {{accessToken}}

