@port = 4000
@baseUrl = http://localhost:{{port}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzg2NTg3N2VjODlkOWE0MzM3NGVhYzQiLCJlbWFpbCI6InVzZXIxMTFAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODEyNzE0MiwiZXhwIjoxNzM4MTI3NDQyfQ.KrMqsdakhQF3x88KC7ApcPmY3vGEmH0QrSnUsdzAAqM
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk5MTA3NmI4OTRlMjI2ZDc3ZTc5MTciLCJlbWFpbCI6Im5ldy11c2VyQG1haWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiJlZDc2YjNjNi1iMzBlLTRkMjEtYWQ5NC04Y2ZkY2YyMDA2ODMiLCJpYXQiOjE3MzgwODUwNDgsImV4cCI6MTc0MDY3NzA0OH0.xQS4xNeNy0_GQZTISYJ_cb8Lmbb4_MK32DBadySBPec
@userId = "67991076b894e226d77e7917"
@postId = cm6ictinr0000s13gdekn4rgu

###
# Новый пост - Видео

POST {{baseUrl}}/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODY1ODc3ZWM4OWQ5YTQzMzc0ZWFjNCIsImVtYWlsIjoidXNlcjExMUBub3Rmb3VuZC5sb2NhbCIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNzM2ODU3NzMzLCJleHAiOjE3MzY4NTgwMzN9.NMZ8DidqS-96nYWENyFjsv8EGjci4Cit2tmeLyTMks4

{
  "type": "video",
  "status": "draft",
  "title": "Great test video!",
  "url": "https://example.com/test",
  "tags": ["politics", "top100"],
  "userId": {{userId}}
}

###
# Список постов
GET {{baseUrl}}/posts?limit=10&sortDirection=asc&page=1 HTTP/1.1

###

# Пост по идентификатору
GET {{baseUrl}}/posts/{{postId}} HTTP/1.1

###

# Удалить пост
DELETE {{baseUrl}}/posts/{{postId}} HTTP/1.1
x-user-id: {{userId}}

###

# обновить пост
PATCH {{baseUrl}}/posts/{{postId}} HTTP/1.1
Content-Type: application/json
x-user-id: {{userId}}

{
  "title": "Gosh, what is this!",
  "tags": ["new_tag", "sport", "run2025"]
}

###
# Лайк
POST {{baseUrl}}/posts/{{postId}}/likes HTTP/1.1
Content-Type: application/json
x-user-id: {{userId}}

###
# Дизлайк
DELETE {{baseUrl}}/posts/{{postId}}/likes HTTP/1.1
Content-Type: application/json
x-user-id: {{userId}}

