@port = 4000
@baseUrl = http://localhost:{{port}}/api
@userId = "67991076b894e226d77e7917"
@postId = cm6o3kbet0000s1o00prlkot1

###
# Новый пост - Видео

POST {{baseUrl}}/posts HTTP/1.1
Content-Type: application/json
x-user-id: {{userId}}

{

  "title": "Great test video!!!!!!!",
  "url": "https://example.com/test",
  "tags": ["politics", "top100"],
  "userId": {{userId}}
}

###
# Список постов
GET {{baseUrl}}/posts?limit=10&sortDirection=asc&page=1 HTTP/1.1

###

# Пост по идентификатору
GET {{baseUrl}}/posts/{{postId}} HTTP/1.1

###

# Удалить пост
DELETE {{baseUrl}}/posts/{{postId}} HTTP/1.1
x-user-id: {{userId}}

###

# обновить пост
PATCH {{baseUrl}}/posts/{{postId}} HTTP/1.1
Content-Type: application/json
x-user-id: {{userId}}

{
  "title": "Gosh, what is this!",
  "tags": ["new_tag", "sport", "run2025"]
}


