@port = 3000
@baseUrl = http://localhost:{{port}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk5MThhYzllYjZjODI2YTBhZjQ4OWEiLCJlbWFpbCI6Im5ldy0tdXNlckBtYWlsLmxvY2FsIiwibmFtZSI6Iktla3MiLCJpYXQiOjE3MzgwODk4NTcsImV4cCI6MTczODA5MDE1N30.YjUu9OLXlsrNJNM8Z8AZM45CnC8rbyKmZPrWnwp0dqY
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk5MTA3NmI4OTRlMjI2ZDc3ZTc5MTciLCJlbWFpbCI6Im5ldy11c2VyQG1haWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiJlZDc2YjNjNi1iMzBlLTRkMjEtYWQ5NC04Y2ZkY2YyMDA2ODMiLCJpYXQiOjE3MzgwODUwNDgsImV4cCI6MTc0MDY3NzA0OH0.xQS4xNeNy0_GQZTISYJ_cb8Lmbb4_MK32DBadySBPec

###
# Новый пользователь
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "email": "new--user@mail.local",
  "name": "Keks",
  "password": "123456",
  "avatar": "path/to/avatar.jpg"
}

###
# Логин в систему
POST {{baseUrl}}/auth HTTP/1.1
Content-Type: application/json

{
  "email": "new--user@mail.local",
  "password": "123456"
}

###
# Информация о пользователе
GET {{baseUrl}}/users/67991076b894e226d77e7917 HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# Подписаться на обновления пользователя

POST {{baseUrl}}/users/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "67991076b894e226d77e7917"
}

###
# Отписаться от обновлений пользователя

POST {{baseUrl}}/users/unsubscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": "67991076b894e226d77e7917"
}

###
# Смена пароля
PATCH {{baseUrl}}/users/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "654321",
  "newPassword": "123456"
}

###
# Refresh token
POST {{baseUrl}}/auth/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}

###
# Check user token
POST {{baseUrl}}/auth/check HTTP/1.1
Authorization: Bearer {{accessToken}}
