# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "use1@notfound.local",
  "name": "Keks",
  "password": "123456",
  "avatar": "path/to/avatar.jpg"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/67935baea3d8ea4b799517a0 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzg2NTg3N2VjODlkOWE0MzM3NGVhYzQiLCJlbWFpbCI6InVzZXIxMTFAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNzcxMDU4NCwiZXhwIjoxNzM3NzEwODg0fQ.WzGePPkm2iYnjCFfRvQcPBKoPpOJ9xXN7qvfPZumhGI

###

# Login user by email and password
POST http://localhost:3000/api/auth HTTP/1.1
Content-Type: application/json

{
  "email": "user111@notfound.local",
  "password": "123456"
}

###

# Login user by email and password
PATCH http://localhost:3000/api/auth/67608860bd69e5b9f659871b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjA4ODYwYmQ2OWU1YjlmNjU5ODcxYiIsIm5hbWUiOiJLZWtzIiwiZW1haWwiOiJ1c2VyQG5vdGZvdW5kLmxvY2FsIn0.lHmVwleHddAnLHp9TR5SveI80RtvbSIeUFriHdxN3Fw

{
  "password": "123456",
  "newPassword": "654321"
}

###
# Refresh token
POST http://localhost:3333/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1NjgwMDA4LCJleHAiOjE3MDgyNzIwMDh9.10Jr7bWOiFTTi42JcMgPh0GVbxa2ikvn8vUVcF8d-AY

###
# Check user token
POST http://localhost:3333/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQwMzJmYmU0Y2FlYjg2OGM2ZWVjMzYiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjgzMTIxMzU1LCJleHAiOjE2ODMxMjE5NTV9.laK4-SAzu_ZMznRVsRWrHxELTGu_P48kpY_CwHPjxtk
